2021-01-22 23:29:13,016 - filename:data_parse_batch_v1.2.py - funcName:_input_master_data_sinkyu - message:数据读取发生错误 - processID:20748
Traceback (most recent call last):
  File "c:/Users/QLQ/Desktop/development/storage/python/my_batch/bin/data_parse_batch_v1.2.py", line 77, in _input_master_data_sinkyu
    raise IOError
OSError
2021-01-22 23:29:13,017 - filename:data_parse_batch_v1.2.py - funcName:_input_master_data_sinkyu - message:数据读取发生错误 - processID:20748
Traceback (most recent call last):
  File "c:/Users/QLQ/Desktop/development/storage/python/my_batch/bin/data_parse_batch_v1.2.py", line 77, in _input_master_data_sinkyu
    raise IOError
OSError
